spring:
  application:
    name: demo
  datasource:
    username: root
    password: 0.00.0
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&amp;characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8886 #tomcat端口号

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.demo.dao: debug